#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

####################
# links to add

my $event = 'nethserver-transmission-update';

# templates to expand
    templates2events( "/etc/samba/smb.conf" , $event );
    templates2events("/etc/httpd/conf.d/transmission-daemon.conf", $event);
    templates2events("/etc/httpd/conf.d/transmission-WebDL.conf", $event);
    templates2events("/etc/httpd/conf.d/default-virtualhost.inc", $event);
    templates2events("/etc/rc.d/rc.local", $event);


# services to launch on event
event_services($event,
    'httpd' => 'reload',
    'smb'=>'restart',
    'nmb'=>'restart');

# actions to perform
event_actions($event,
    'initialize-default-databases' => '00',
    'nethserver-transmission-services-conf' => '01',
    'nethserver-transmission-watchedDir-conf'=>'02');

my $event = 'nethserver-transmission-save';
    templates2events( "/etc/samba/smb.conf" , $event );
    templates2events("/etc/httpd/conf.d/transmission-daemon.conf", $event);
    templates2events("/etc/httpd/conf.d/transmission-WebDL.conf", $event);
    templates2events("/etc/httpd/conf.d/default-virtualhost.inc", $event);

# services to launch on event
event_services($event,
    'httpd' => 'reload',
    'smb'=>'restart',
    'nmb'=>'restart');

# actions to perform
event_actions($event,
    'nethserver-transmission-services-conf' => '01',
    'nethserver-transmission-watchedDir-conf'=>'02');


my $event = 'trusted-networks-modify';
templates2events("/etc/httpd/conf.d/transmission-daemon.conf", $event);
templates2events("/etc/httpd/conf.d/transmission-WebDL.conf", $event);
event_services($event, 'httpd' => 'reload');
