#!/usr/bin/perl

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;
use NethServer::ApiTools;

my $input = NethServer::ApiTools::readInput();
my $cmd = $input->{'action'};
my $db = esmith::ConfigDB->open_ro();

my $ret = {};

if ( $cmd eq "app-info") {
    my $status = $db->get_prop('transmission','status')|| 'disabled';
    my $name = $db->get_prop('transmission-daemon','Name')|| 'transmission';
    if ($status eq "enabled") {
            my $host = $input->{'location'}->{'hostname'} || '';
            $ret = {
                'url' => "https://$host/$name"
            }
    }
}

elsif ($cmd eq 'configuration') {
    my %transmission = (
        Users => $db->get_prop('transmission','Users') || '',
        Webaccess => $db->get_prop('transmission','Webaccess') || 'private',
        status => $db->get_prop('transmission','status') || 'disabled'
    );
    $ret->{'configuration'} = \%transmission;
} else {
    NethServer::ApiTools::error();
}

print encode_json($ret);
