#!/usr/bin/php
<?php
/*
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/
require_once("/usr/libexec/nethserver/api/lib/Helpers.php");
$data = readInput();
$v = new LegacyValidator($data);
$cmd = $data['action'];
$cdb = new EsmithDatabase('configuration');

if ($data['action'] == 'configuration') {
    // settings validator
    $v->declareParameter('status',Validate::SERVICESTATUS);
    $users = $v->createValidator(Validate::USERNAME);
    foreach (explode(',',$data['Users']) as $u) {
        if (!$users->evaluate($u)) {
            $v->addValidationError('Users', 'not_valid_username', $u);
        }
    }
    $v->declareParameter('Webaccess', $v->createValidator()->memberOf('public','private'));
}
# Validate the input
if ($v->validate()) {
    success();
} else {
    error($v);
}
